package:
  name: memory_profiler
  version: "0.33"

source:
  fn: memory_profiler-0.33.tar.gz
  url: https://pypi.python.org/packages/source/m/memory_profiler/memory_profiler-0.33.tar.gz
  md5: 9debea7238d9837b20aa99751cebbe08

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: http://pypi.python.org/pypi/memory_profiler
  license: BSD License
  summary: 'A module for monitoring memory usage of a python program'
