package:
  name: hampy
  version: "1.4.0"

source:
  fn: hampy-1.4.0.tar.gz
  url: https://pypi.python.org/packages/source/h/hampy/hampy-1.4.0.tar.gz
  md5: d756388c69acffc732fc35819611898e
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - hampy = hampy:main
    #
    # Would create an entry point called hampy that calls hampy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - setuptools-git
    - numpy
    - matplotlib
    - scipy
    - opencv
    - pillow

  run:
    - python
    - numpy
    - matplotlib
    - scipy
    - opencv
    - pillow

test:
  # Python imports
  imports:
    - hampy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/pierre-rouanet/hampy
  license: GNU GENERAL PUBLIC LICENSE Version 3
  summary: 'Simple Hamming Marker Detection using OpenCV'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
