# Tested on Mac OS X 10.9 using clang compiler provided by XCode
package:
    name: opencv
    version: 3.0.0

source:
    fn: opencv-3.0.0.zip
    url: http://downloads.sourceforge.net/project/opencvlibrary/opencv-unix/3.0.0/opencv-3.0.0.zip

build:
    number: 0

requirements:
    build:
        - cmake
        - numpy
        - jpeg
        - zlib
        - libpng
        - python
        - ffmpeg

    run:
        - python
        - numpy
        - jpeg
        - zlib
        - libpng
        - ffmpeg

test:
    imports:
      - cv2

about:
    home: http://opencv.org/
    license: BSD
