package:
  name: pixman
  version: 0.32.6

source:
  fn: pixman-0.32.6.tar.gz
  url: http://cairographics.org/releases/pixman-0.32.6.tar.gz
  patches:
    - no_test.patch      [win]

build:
  features:
    - vc9                [win and py27]
    - vc10               [win and py34]
    - vc14               [win and py35]

about:
  home: http://cairographics.org
  license: LGPL 2.1 and MPL 1.1
